{% set python_min = '3.11' %}
{% set name = "serapeum_utils" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Serapieum-of-alex/serapeum_utils/archive/{{ version }}.tar.gz
  sha256: 38d70727caa64613cd46d08407c9ae09733b1847c37c395af1ecce61574981f0

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core >=1.0.0
  run:
    - python >={{ python_min }}

test:
  imports:
    - serapeum_utils
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Serapieum-of-alex/serapeum_utils
  license:  GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: decorators for handling function with too many parameters
  description: |
    utility package with various functionality to handling functions with too many parameters, save and read pikled objects.
  dev_url: https://github.com/Serapieum-of-alex/serapeum_utils
  doc_url: https://serapeum_utils.readthedocs.io/

extra:
  recipe-maintainers:
    - MAfarrag
