{% set name = "serapeum_utils" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Serapieum-of-alex/serapeum_utils/archive/{{ version }}.tar.gz
  sha256: e3e6fd95c00dbcf7bc8b2201b1d591bf1505e40f1fd694ab773d78c2b48cf05d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9,<3.11
    - pip
    - poetry-core >=1.0.0
  run:
    - python >=3.9,<3.11

test:
  imports:
    - serapeum_utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Serapieum-of-alex/serapeum_utils
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: decorators for handling function with too many parameters
  description: |
    utility package with various functionality to handling functions with too many parameters, save and read pikled objects.
  dev_url: https://github.com/Serapieum-of-alex/serapeum_utils
  doc_url: https://serapeum_utils.readthedocs.io/

extra:
  recipe-maintainers:
    - MAfarrag
